#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & 10 Buster 64 bit               #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Created By Dope~Kid                           #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# Git Hub                                       #"
echo -e "# JESUS                                         #"
echo -e "# ME                                            #"
echo -e "# Stack Exchange                                #"
echo -e "# Do Promo                                      #"
echo -e "# YOU ARE NOOB                                  #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
